name: 'Update schedule'
# 关键：授予写入权限
permissions:
  contents: write

on:
  schedule:
    - cron: '22 3,19 * * *'
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          update-environment: true
          cache: 'pipenv'

      - name: Install pipenv
        run: pip3 install --user pipenv

      - name: Install dependencies
        run: |
          pipenv lock
          pipenv --python 3.13
          pipenv install

      - name: Update EPG
        run: pipenv run epg

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          [[ -f "output/epg.xml" ]] && git add -f "output/epg.xml"
          [[ -f "output/epg.gz" ]] && git add -f "output/epg.gz"
          
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git push origin master
          fi

      - name: Mirror GitHub to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/lhbox1/myEPG'
          dst: 'gitee/mytv-android'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          force_update: true
          static_list: "myEPG"
          account_type: org
          debug: true
