name: 'Update schedule'
# 关键：授予写入权限
permissions:
  contents: write
  actions: write # 清理运行记录必须

on:
  schedule:
    - cron: '22 3 */3 * *'
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          update-environment: true
          cache: 'pipenv'

      - name: Install pipenv
        run: pip3 install --user pipenv

      - name: Install dependencies
        run: |
          pipenv lock
          pipenv --python 3.13
          pipenv install

      - name: Update EPG
        run: pipenv run epg

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          [[ -f "output/epg.xml" ]] && git add -f "output/epg.xml"
          [[ -f "output/epg.gz" ]] && git add -f "output/epg.gz"
          
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git push origin master
          fi

  # 替换为更稳定的清理插件
  cleanup:
    runs-on: ubuntu-latest
    needs: push # 在 push 任务成功完成后执行
    steps:
      - name: Delete old workflow runs
        uses: Alistair23/the-delete-workflow-runs@v2.3.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0             # 不按天数筛选
          keep_minimum_runs: 3       # 严格保留最近的 3 个记录
